apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: softethervpn
spec:
  selector:
    matchLabels:
      app: softethervpn
  serviceName: "softethervpn"
  replicas: 1
  template:
    metadata:
      labels:
        app: softethervpn
    spec:
      containers:
      - name: softethervpn
        image: basdp/softethervpn-docker:latest
        ports:
        - name: management
          containerPort: 5555
          protocol: TCP
        - name: openvpn
          containerPort: 1194
          protocol: UDP
        - name: management2
          containerPort: 992
          protocol: TCP
        - name: ipsec-ike
          containerPort: 500
          protocol: UDP
        - name: ipsec-nat
          containerPort: 4500
          protocol: UDP
        - name: l2tp
          containerPort: 1701
          protocol: UDP
        volumeMounts:
        - mountPath: "/etc/vpnserver"
          name: softethervpn-pv
  volumeClaimTemplates:
  - metadata:
      name: softethervpn-pv
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi

---

apiVersion: v1
kind: Service
metadata:
  name: softethervpn
spec:
  selector:
    app: softethervpn
  type: NodePort
  ports:
  - name: management
    protocol: TCP
    port: 5555
    nodePort: 30555
  - name: ipsec-nat
    protocol: UDP
    port: 4500
    nodePort: 30450
  - name: ipsec-ike
    protocol: UDP
    port: 500
    nodePort: 30500
  - name: l2tp
    protocol: UDP
    port: 1701
    nodePort: 31701
