kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: softethervpn-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: softethervpn
spec:
  selector:
    matchLabels:
      app: softethervpn
  replicas: 1
  template:
    metadata:
      labels:
        app: softethervpn
    spec:
      volumes:
      - name: softethervpn-pv-storage
        persistentVolumeClaim:
          claimName: softethervpn-pv-claim
      containers:
      - name: softethervpn
        image: basdp/softethervpn-docker:latest
        ports:
        - name: management
          containerPort: 5555
          protocol: TCP
        - name: openvpn
          containerPort: 1194
          protocol: UDP
        - name: management2
          containerPort: 992
          protocol: TCP
        - name: ipsec-ike
          containerPort: 500
          protocol: UDP
        - name: ipsec-nat
          containerPort: 4500
          protocol: UDP
        - name: l2tp
          containerPort: 1701
          protocol: UDP
        volumeMounts:
        - mountPath: "/etc/vpnserver"
          name: softethervpn-pv-storage

---

apiVersion: v1
kind: Service
metadata:
  name: softethervpn
spec:
  selector:
    app: softethervpn
  type: NodePort
  ports:
  - name: management
    protocol: TCP
    port: 5555
    nodePort: 35555
  - name: ipsec-nat
    protocol: UDP
    port: 4500
    nodePort: 34500
  - name: ipsec-ike
    protocol: UDP
    port: 500
    nodePort: 30500
  - name: l2tp
    protocol: UDP
    port: 1701
    nodePort: 31701
